### ISSUE TITLE
giving error after deployed to heroku

### ISSUE THREAD

**Issue by todokku** [meneses-pt/videogoals#3]
https://goalsvideo.herokuapp.com/
what is 'DB_ENGINE' value for using herokupostgresql addon or any other free db addons exist on heroku addons ?
finest regards

**Comment by meneses-pt** [comment]
The DB_ENGINE value for a Postgres DB should be 'django.db.backends.postgresql'. This has nothing to do with it being a Heroku addon.
Accessing that link, I can see that you should add that address to the line https://github.com/meneses-pt/videogoals/blob/a7db8218c90fb7efd79de3bc5bf93bca539fa001/videogoals/settings.py#L29 or change its value to ['*']
