### ISSUE TITLE
[Question] How did you find SofaScore?

### ISSUE THREAD

**Issue by nicbaughman** [meneses-pt/videogoals#4]
I really enjoy watching the changes and iterations you are making. I don't see an issue but more have a comment.

How did you find SofaScore and know that you can use that URL to get a JSON format of essentially all matches daily?  That is absolutely brilliant.

Are there any API limits? I am guessing no as you can just do a simple GET to find that info.

EDIT: This commit is what I am referring to -> https://github.com/meneses-pt/videogoals/commit/dad97c06fdd8c0f26585dd17cc16dc1bc9312a13

**Comment by meneses-pt** [comment]
I was thinking about scraping SofaScore, as the API I was using is really poor. (For example, didn't even had the Spanish Supercopa matches).
When I started investigating SofaScore, I saw a bunch of API requests being made to fill the information on their webpage.
I fetched that data for some hours to test for access limits and had no issues, but two days after putting that online, I noticed that the data wasn't updating.
I found out they had just blocked my IP for any query to their site or API endpoints.
I contacted them to see if they could somehow givee access or tell me their limits, but they said they couldn't allow that, as it would go against the contract they have with their data providers.
I already had exchanged the data from the teams, etc. and it was not something I could easily revert, so I had to improvise (Which I still am).
I scrap the sslproxies.org website for https proxies, and try some of them to access SofaScore without being blocked. That has worked for now, and I still didn't have a better idea (I'm open for suggestions).

There is a bunch of other information that I intend to use from SofaScore. They have a "media" section, that has official videos, and I can use those on my website and, on their mobile app, a section where they put tweets with certain hashtags for each match, that usually contain videos for that match. I think I will use that too as an additional video source.

Any comments or suggestions are welcome. And if you want me to clarify on something, just let me know.

Also, if you want, you can contact me directly. It shouldn't be difficult to find out my email address.
